<%@ Page Title="" Language="C#" MasterPageFile="~/admin/AdminMasterPage.master" AutoEventWireup="true" CodeFile="view customer.aspx.cs" Inherits="admin_view_customer" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
        
    <asp:TextBox ID="txtSearch" runat="server" ></asp:TextBox>
<asp:Button Text="Search" runat="server" OnClick="Search"/>
<hr />
<asp:GridView ID="customer" runat="server" AllowPaging="True"
    OnPageIndexChanging="OnPaging" CellPadding="4" GridLines="Horizontal" onrowediting="customer_RowEditing" onrowcancelingedit="customer_RowCancelingEdit"
    onrowupdating="customer_RowUpdating" AllowSorting="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" Width="352px" AutoGenerateColumns="False" DataKeyNames="regid" BackColor="White" BorderColor="#336666" BorderStyle="Double" BorderWidth="3px"     >
   
    <Columns>
        <asp:BoundField DataField="regid" HeaderText="regid" InsertVisible="False" ReadOnly="True" SortExpression="regid" />
        <asp:BoundField DataField="fname" HeaderText="fname" SortExpression="fname" />
        <asp:BoundField DataField="lname" HeaderText="lname" SortExpression="lname" />
        <asp:BoundField DataField="address" HeaderText="address" SortExpression="address" />
        <asp:BoundField DataField="postcode" HeaderText="postcode" SortExpression="postcode" />
        <asp:BoundField DataField="username" HeaderText="username" SortExpression="username" />
    </Columns>
   
    <FooterStyle BackColor="White" ForeColor="#333333" />
    <HeaderStyle BackColor="#336666" Font-Bold="True" ForeColor="White" />
    <PagerStyle BackColor="#336666" ForeColor="White" HorizontalAlign="Center" />
    <RowStyle BackColor="White" ForeColor="#333333" />
    <SelectedRowStyle BackColor="#339966" Font-Bold="True" ForeColor="White" />
    <SortedAscendingCellStyle BackColor="#F7F7F7" />
    <SortedAscendingHeaderStyle BackColor="#487575" />
    <SortedDescendingCellStyle BackColor="#E5E5E5" />
    <SortedDescendingHeaderStyle BackColor="#275353" />
   
</asp:GridView>
  
    
  
    
  
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=&quot;H:\Desktop\Mobile Eshop\Mobile E-shop\App_Data\mobileEshop.mdf&quot;;Integrated Security=True;Connect Timeout=30" ProviderName="System.Data.SqlClient" SelectCommand="SELECT [regid], [fname], [lname], [address], [postcode], [username] FROM [tbl_register]"></asp:SqlDataSource>
  
    
  
    
  

    
  
    
  
  
    
  
    
  

  
</asp:Content>

